language: cpp

compiler: 
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:wxformbuilder/wxwidgets
  - sudo add-apt-repository -y ppa:chris-lea/protobuf
  - sudo apt-get update -qq
  - sudo apt-get install -qq --assume-yes graphviz doxygen libwxgtk3.0-dev libprotobuf-dev protobuf-compiler
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

before_script:
  - mkdir build
  - cd build
  - cmake -DBUILD_USE_CLANG_FORMAT=OFF -DBUILD_USE_CPPLINT=OFF -DBUILD_USE_DOXYGEN=OFF -DBUILD_USE_DOXYGEN_GLOBAL=OFF -DBUILD_USE_CPPCHECK=OFF -DUSE_WXWIDGETS_LEGACY_FINDTEXT=ON -DUSE_CPP_AS_RUST=ON ..

script: make
